### ISSUE TITLE
As a designer, I think the player's ship should feel consistently useful in a fight. Because of the need to defend the cargo ship while outnumbered the player must feel individually powerful. 

### ISSUE THREAD

**Issue by Tmac4930** [AngeloCM/TheLastShip#5]

**Comment by luke-goldfain** [comment]
For this reason we should probably brainstorm features such as an area-of-effect bomb, lock-on, and homing weapons. Considering movement abilities is important for this as well. If the player is only able to shoot forward, they will probably feel powerless a lot of the time.
